/*
* clock driver for BST A1000
* This file contains proprietary information that is the sole intellectual 
* property of Black Sesame Technologies, Inc. and its affiliates. 
* No portions of this material may be reproduced in any 
* form without the written permission of: 
* Black Sesame Technologies, Inc. and its affiliates 
* 2255 Martin Ave. Suite D
* Santa Clara, CA 95050 
* Copyright @2016: all right reserved. 
*/

#ifndef _CLOCK_BST_A1000_H
#define _CLOCK_BST_A1000_H

#define MAIN_OSC_CLK                    (0)
#define CLK_400_SYSNOC_WORK             (1)
#define LB_CPU_CLK                      (2)
#define LB_CPU_DSU_CLK                  (3)
#define CLK_800_CORENOC_WORK            (4)
#define CLK_800_CPUNOC_WORK             (5)
#define LB_MATRIX_SYSNOC_APB_S_PCLK     (6)
#define SAFE_NOC_ACLK                   (7)
#define SAFE_NOC_HCLK                   (8)
#define SAFE_NOC_PCLK                   (9)
#define LB_LPDDR0_S0_ACLK               (10)
#define LB_LPDDR0_S1_ACLK               (11)
#define LB_LPDDR0_S2_ACLK               (12)
#define LB_LPDDR0_S3_ACLK               (13)
#define LB_LPDDR1_S0_ACLK               (14)
#define LB_LPDDR1_S1_ACLK               (15)
#define LB_LPDDR1_S2_ACLK               (16)
#define LB_LPDDR1_S3_ACLK               (17)
#define LB_LPDDR0_PCLK                  (18)
#define LB_LPDDR1_PCLK                  (19)
#define QSPI0_HCLK                      (20)
#define QSPI0_WCLK                      (21)
#define QSPI1_HCLK                      (22)
#define QSPI1_WCLK                      (23)
#define GIC_WCLK                        (24)
#define LSP0_PCLK                       (25)
#define LSP0_WCLK                       (26)
#define LSP0_I2SM_CLK                   (27)
#define UART_WCLK                       (28)
#define CAN_FD0_WCLK                    (29)
#define CAN_FD1_WCLK                    (30)
#define LSP1_PCLK                       (31)
#define LSP1_WCLK                       (32)
#define LB_PCIE_REF_ALT_CLK_P           (33)
#define LB_PCIE_AXI_ACLK                (34)
#define LB_PCIE_AUX_CLK                 (35)
#define LB_PCIE_APB_PCLK                (36)
#define LB_GMAC0_WCLK                   (37)
#define LB_GMAC1_WLCK                   (38)
#define LB_GMAC0_AXIM_ACLK              (39)
#define LB_GMAC1_AXIM_ACLK              (40)
#define LB_GMAC0_APB_S_PCLK             (41)
#define LB_GMAC1_APB_S_PCLK             (42)
#define LB_GMAC0_PTP_CLK                (43)
#define LB_GMAC1_PTP_CLK                (44)
#define LB_USB2_AHB_HCLK                (45)
#define LB_USB2_REF_ALT_CLK             (46)
#define LB_USB2_APB_PCLK                (47)
#define LB_USB3_SUSPEND_CLK             (48)
#define LB_USB3_REF_ALT_CLK             (49)
#define LB_USB3_AXI_ACLK                (50)
#define LB_USB3_APB_PCLK                (51)
#define LB_SDEMMC0_W_BCLK               (52)
#define LB_SDEMMC0_HCLK                 (53)
#define LB_SDEMMC1_W_BCLK               (54)
#define LB_SDEMMC1_HCLK                 (55)
#define LB_GDMA_CORE_CLK                (56)
#define LB_GDMA_AXI_ACLK                (57)
#define LB_GDMA_AHB_CLK                 (58)
#define LB_CV_CORE_CLK                  (59)
#define LB_CV_AXIM0_CLK                 (60)
#define LB_CV_AXIM1_CLK                 (61)
#define LB_CV_AXIS_CLK                  (62)
#define LB_NET_CLK                      (63)
#define LB_NET_DSPCORE_CLK              (64)
#define LB_ISP_SCLK                     (65)
#define LB_ISP_AHB_HCLK                 (66)
#define LB_MIPI0_PHY_CFG_CLK            (67)
#define LB_MIPI1_PHY_CFG_CLK            (68)
#define LB_MIPI2_PHY_CFG_CLK            (69)
#define LB_MIPI0_APB_CFG_CLK            (70)
#define LB_MIPI1_APB_CFG_CLK            (71)
#define LB_MIPI2_APB_CFG_CLK            (72)
#define LB_VSP_DISP_CLK                 (73)
#define LB_VSP_CLK                      (74)
#define LB_VSP_AHB_CLK                  (75)
#define LB_GPU_AXI_ACLK                 (76)
#define LB_GPU_APB_S_PCLK               (77)
#define IPC_APB_S_PCLK                  (78)
#define TEMPSENSOR_1M25_CLK             (79)
#define TEMP_25M_CLK                    (80)
#define LSP0_UART0_WCLK                 (81)
#define LSP0_UART0_PCLK                 (82)
#define LSP0_UART1_WCLK                 (83)
#define LSP0_UART1_PCLK                 (84)
#define LSP1_UART0_WCLK                 (85)
#define LSP1_UART0_PCLK                 (86)
#define LSP1_UART1_WCLK                 (87)
#define LSP1_UART1_PCLK                 (88)
#define LSP0_I2C0_WCLK                  (89)
#define LSP0_I2C1_WCLK                  (90)
#define LSP0_I2C2_WCLK                  (91)
#define LSP0_I2C0_PCLK                  (92)
#define LSP0_I2C1_PCLK                  (93)
#define LSP0_I2C2_PCLK                  (94)
#define LSP1_I2C3_WCLK                  (95)
#define LSP1_I2C4_WCLK                  (96)
#define LSP1_I2C5_WCLK                  (97)
#define LSP1_I2C3_PCLK                  (98)
#define LSP1_I2C4_PCLK                  (99)
#define LSP1_I2C5_PCLK                  (100)
#define LSP0_TIMER0_WCLK                (101)
#define LSP0_TIMER0_PCLK                (102)
#define LSP0_TIMER1_WCLK                (103)
#define LSP0_TIMER1_PCLK                (104)
#define LSP1_TIMER2_WCLK                (105)
#define LSP1_TIMER2_PCLK                (106)
#define LSP1_TIMER3_WCLK                (107)
#define LSP1_TIMER3_PCLK                (108)
#define LSP0_SPI0_WCLK                  (109)
#define LSP0_SPI0_PCLK                  (110)
#define LSP1_SPI1_WCLK                  (111)
#define LSP1_SPI1_PCLK                  (112)
#define LSP0_WDT0_WCLK                  (113)
#define LSP0_WDT0_PCLK                  (114)
#define LSP0_WDT1_WCLK                  (115)
#define LSP0_WDT1_PCLK                  (116)
#define LSP1_WDT2_WCLK                  (117)
#define LSP1_WDT2_PCLK                  (118)
#define LSP1_WDT3_WCLK                  (119)
#define LSP1_WDT3_PCLK                  (120)
#define LSP0_I2SM_SCK                   (121)
#define LSP0_I2SM_PCLK                  (122)
#define LSP1_I2SS_SCK                   (123)
#define LSP1_I2SS_PCLK                  (124)
#define LSP0_GPIO_PCLK                  (125)
#define LSP1_GPIO_PCLK                  (126)
#define CAN_FD0_PCLK                    (127)
#define CAN_FD1_PCLK                    (128)


#define CLK_MAX                         (129)

#endif /* _CLOCK_BST_A1000_H */
