# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux BST PWM drivers.
#
#obj-$(CONFIG_BST_DUMP_REGISTER)           += bst_dump_reg.o canfd_dump.o qspi_dump.o irq_gic_dump.o pwm_dump.o wdt_dump.o usb_dump.o
obj-$(CONFIG_BST_DUMP_REGISTER) += bst_dump.o
bst_dump-y := bst_dump_reg.o canfd_dump.o qspi_dump.o irq_gic_dump.o pwm_dump.o wdt_dump.o usb_dump.o
