obj-y := jaguar1.o
jaguar1-objs := jaguar1_drv.o jaguar1_i2c.o jaguar1_video.o jaguar1_coax_protocol.o jaguar1_motion.o jaguar1_video_eq.o jaguar1_mipi.o #imx_mipi.o

#subdir-ccflags-y += -DFOR_IMX6
subdir-ccflags-y += -DNC_DEBUG



