# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux BST SOC drivers.
#

obj-$(CONFIG_BST_DDR_ECC_INT)           += bst_ddr_ecc_int.o
obj-$(CONFIG_BST_KERNEL_NETLINK)	+= bst_netlink_safety.o

obj-y					+= bst_boardconfig.o
obj-y				+= dump_module/
