# BST clock specific Makefile
ifeq ($(CONFIG_COMMON_CLK_BSTA1000A),y)
obj-y	+= clk-a1000.o
obj-y	+= clk-a1000-test.o
else ifeq ($(CONFIG_COMMON_CLK_BSTA1000B),y)
obj-y	+= clk-a1000b.o
obj-y	+= clk-a1000b-test.o
endif




