# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BST_OPTEE) += bst_optee.o
bst_optee-objs += call_sec.o
bst_optee-objs += tee_interface.o
bst_optee-objs += tee_read.o
bst_optee-objs += tee_client_api.o
