# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Bst CV GWARP SCALER

# loadable module
# export symbol 

obj-y += bst_gwarp_driver.o
bst_gwarp_driver-y = bst_cv_gwarp.o bst_cv_gwarp_miscdev.o bst_cv_sg_mem_manager.o bst_cv.o 

#subdir-ccflags-y := -g -DDEBUG

